export { DashboardPage } from "./components/dashboard/dashboard-page";
export { AppointmentsPage } from "./components/appointments/appointments-page";
export { ArrivalBoardPage } from "./components/arrival-board/arrival-board-page";
export { ReceptionChatPage } from "./components/chat/reception-chat-page";
export { CommunicationsPage } from "./components/communications/communications-page";
export { PriorityQueuePage } from "./components/priority-queue/priority-queue-page";
export { SchedulingPage } from "./components/scheduling/scheduling-page";
export { DoctorAvailabilityPage } from "./components/availability/doctor-availability-page";
export { useReceptionRealtime } from "./hooks/use-reception-realtime";
